### ISSUE TITLE
Add the map in the full view

### ISSUE THREAD

**Issue by CannonLock** [osg-htc/maps-archive#2]
Add a react globe. Looks around if there are other libraries for this. Things to looks for are stars and last time it was updated. One thing I like about macrostrat.org is that you can switch from the globe to the flat view ( Button in the bottom right ).

**Comment by djw8605** [comment]
If you are looking for other options, I've used [Mapbox](https://www.mapbox.com/) lately for my projects.  It can be either a globe or flat.  For example, I used it for a [NRP Website](https://nrp-website.vercel.app/).  I went back and forth if it should be a glob or flat, and the styling.  I used the library [react-map-gl](https://visgl.github.io/react-map-gl/) for interacting with the map.

**Comment by CannonLock** [comment]
Example website: https://github.com/djw8605/nrp-website
